name: "shift"
version: "1.0.0"
config-version: 2
profile: "shift"

model-paths: ["models"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  shift:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: gold
